# Generated by Django 5.2.4 on 2025-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_categories_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
