# Generated by Django 5.2.4 on 2025-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_categories_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
